version: "3.3"

services:
  nginx:
    image: nginx
    volumes:
      - ./server/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/opt/back:cached
    ports:
      - ${NGINX_PORT}:80
    networks:
      - network
    depends_on:
      - backend
      - database

  backend:
    image: bitnami/php-fpm:7.4.29
    volumes:
      - ./src:/opt/back
    working_dir: /opt/ba
    networks:
      - network
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - network
    ports:
      - ${DATABASE_PORT}:3306


networks:
  network:
    driver: bridge

